# Generated by Django 4.1.7 on 2023-03-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigger', '0002_alter_campaignlead_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(null=True, to='jigger.contacttag'),
        ),
    ]
