# Generated by Django 4.1.7 on 2023-03-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigger', '0003_alter_contact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignlead',
            name='stage',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
