# Generated by Django 4.1.7 on 2023-03-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigger', '0005_alter_campaignlead_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='contacts',
            field=models.ManyToManyField(blank=True, through='jigger.CampaignLead', to='jigger.contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, to='jigger.contacttag'),
        ),
    ]
