# Generated by Django 4.1.7 on 2023-03-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jigger', '0006_alter_campaign_contacts_alter_contact_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnelevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jigger.funnelevent'),
        ),
    ]
