# Generated by Django 4.1.7 on 2023-03-10 20:46

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigger', '0007_funnelevent_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignlead',
            old_name='state',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='campaignlead',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Dead'), (2, 'In Funnel'), (3, 'Converted'), (4, 'Cancelled')], default=0),
        ),
        migrations.AddField(
            model_name='campaignlead',
            name='state',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
