# Generated by Django 4.1.7 on 2023-03-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jigger', '0010_alter_funnelevent_options_alter_funnelevent_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='provider',
            new_name='driver',
        ),
    ]
