# Generated by Django 4.1.7 on 2023-03-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigger', '0013_alter_funnelevent_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnelevent',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='funnelevent',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
