# Generated by Django 4.1.7 on 2023-03-13 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jigger', '0014_alter_funnelevent_action_alter_funnelevent_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnelevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
