# Generated by Django 4.1.7 on 2023-07-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigger', '0015_alter_funnelevent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ceased',
            field=models.BooleanField(default=False),
        ),
    ]
