"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l63lu*nrq^aj6hqeoqtecpl-2=7i)0cq2l8w%2$(hbk-!7kh63'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = not 'PRODUCTION' in os.environ

ALLOWED_HOSTS = ['*']
#[
#    'localhost', 'crm.qwes.me', 'qwes.me'
#]

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    "https://crm.qwes.me",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'background_task',
    'usher',
    'hooker',
    'jigger',
    'teaser',
    'cabin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': 'localhost',
        'PORT': '5432',
        'USER': 'crm',
        'PASSWORD': 'xxxxxxxxxxx',
        'NAME': 'crm',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# "Teaser" app settings
TEXT_MESSAGE_MAX_BATCH = 1000
TEXT_MESSAGE_PROVIDER = 'OMNICELL'
TEXT_MESSAGE_CHECK_SECS = 10

# Omnicell settings
OMNICELL_USERNAME = 'try802bb361b134c005cc1306c098327'
OMNICELL_PASSWORD = '2f8Y144mBttkmnkgl'
OMNICELL_ALPHANAMES = ['Omni']

# URL Shortener settings
#SHORTENER_ABSOLUTE_URL = 'https://qwes.me/'
SHORTENER_ABSOLUTE_URLS = [ 'https://qwes.me/', 'https://finc.me/', 'https://uys.ink/', 'https://yus.ink/' ]
SHORTENER_SITE_MAP = {
    'https://site/':
    [ 
        'https://na-vse.store/', 'https://na-vse.shop/',
        'https://bab-lo.shop/', 'https://bab-lo.store/',
        'https://babosik.shop/', 'https://babosik.store/',
        'https://cash-online.shop/',
        'https://cashonlines.store/',
        'https://deng-i.store/',
        'https://dollary.shop/', 'https://dollary.store/',
        'https://kreditik.store/', 'https://kreditik.shop/',
        'https://kreditok.shop/',
        'https://ok-crdt.shop/'
    ]
}
