# Generated by Django 4.1.7 on 2023-02-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.TextField()),
                ('short_url', models.CharField(db_index=True, max_length=50, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('max_count', models.IntegerField(default=-1)),
                ('lifespan', models.IntegerField(default=-1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expired', models.DateTimeField()),
            ],
        ),
    ]
