# Generated by Django 4.1.7 on 2023-03-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jigger', '0002_alter_campaignlead_state'),
        ('usher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmap',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jigger.funnelevent'),
        ),
    ]
