# Generated by Django 4.1.7 on 2023-03-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jigger', '0002_alter_campaignlead_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessageBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=15)),
                ('internal_id', models.BigIntegerField()),
                ('finalized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1000)),
                ('internal_id', models.BigIntegerField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'En Route'), (2, 'Delivered'), (3, 'Expired'), (4, 'Rejected')], default=0)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teaser.textmessagebatch')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jigger.funnelevent')),
            ],
        ),
    ]
