# Generated by Django 4.1.7 on 2023-03-05 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jigger', '0006_alter_campaign_contacts_alter_contact_tags'),
        ('teaser', '0002_textmessage_recipient_alter_textmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teaser.textmessagebatch'),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='internal_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jigger.funnelevent'),
        ),
    ]
