# Generated by Django 4.1.7 on 2023-03-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaser', '0004_alter_textmessagebatch_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessagebatch',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
