# Generated by Django 4.1.7 on 2023-03-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaser', '0005_textmessagebatch_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textmessagebatch',
            options={'verbose_name_plural': 'text message batches'},
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='internal_id',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textmessagebatch',
            name='internal_id',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
