# Generated by Django 4.1.7 on 2023-03-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaser', '0007_alter_textmessage_internal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
